### ISSUE TITLE
Error setting up entry Configuration.yaml for sonos_cloud

### ISSUE THREAD

**Issue by 5thsymphony** [jjlawren/sonos_cloud#14]
I installed this extension the other day (2 releases ago, version 0.0.1 I believe it was) which worked fine.

After updating to the current release I saw that the media_player entities had not been merged. I therefore removed the extension from Home Assistant (not from Hacs, just from the configurations page). 

When I try and add the extension again I get the following error:

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 313, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/sonos_cloud/__init__.py", line 99, in async_setup_entry
    hass.data[DOMAIN][PLAYERS].extend(players)
KeyError: 'players'
```

Home Assistant 2021.12.8 running on HassOS

If you need any more information I'm more than happy to help debug.

**Comment by 5thsymphony** [comment]
After restarting Home Assistant trying to get better debug logs this now works fine. Closing for now.
