### ISSUE TITLE
2022.8.x integration problem

### ISSUE THREAD

**Issue by schol478** [jjlawren/sonos_cloud#33]
Integration problem since new version of home assistant.

Can someone help me?

This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/sonos_cloud/__init__.py:122
Integration: Sonos Cloud (documentation, issues)
First occurred: August 8, 2022 at 15:37:02 (3 occurrences)
Last logged: 08:26:46

Error setting up entry HA for sonos_cloud
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 357, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/sonos_cloud/__init__.py", line 122, in async_setup_entry
    hass.data[DOMAIN][PLAYERS].extend(players)
KeyError: 'players'

**Comment by jjlawren** [comment]
Does this happen consistently if you restart HA? Any other errors in your logs?

**Comment by craigwitter** [comment]
I'm seeing the same thing too. Mine seems to have only broken since last night's update to 2022.8.4. Using version of sonos cloud 0.3.1.
Error:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 357, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/sonos_cloud/__init__.py", line 122, in async_setup_entry
    hass.data[DOMAIN][PLAYERS].extend(players)
KeyError: 'players'

**Comment by jjlawren** [comment]
I can reproduce this when reloading the integration. Will push a fix shortly.
